<?php

return [
    'bot_name' => 'KrimAI',
    'widget_title' => 'KrimAI — Institute Assistant',
    'welcome' => 'Hello! I\'m KrimAI, the virtual assistant of the Criminology Research Institute. Ask me about the institute, its research projects, international cooperation, or contact details.',
    'placeholder' => 'Type your question...',
    'send' => 'Send',
    'thinking' => 'KrimAI is typing...',
    'disclaimer' => 'Answers are generated by AI based on the institute\'s data and may contain inaccuracies.',
    'error_generic' => 'Sorry, I could not respond right now. Please try again shortly or reach us via the contact page.',
    'error_config' => 'The chatbot is not configured yet.',

    'about_paragraph' => 'The Criminology Research Institute (full name: Criminology Research Institute of the Republic of Uzbekistan) is a state scientific institution engaged in research on crime and public safety. The Institute studies the causes and trends of crime, develops prevention mechanisms, publishes scientific journals and analytical materials, and cooperates with foreign countries and international organizations.',

    'knowledge_intro' => 'Below is official information about the institute. Answer using only this information.',
    'councils_label' => 'Scientific councils',
    'leadership_label' => 'Leadership',
    'contact_label' => 'Contact details',
    'projects_label' => 'Research projects',
    'journals_label' => 'Scientific journals',
    'sections_label' => 'Website sections',
];
